version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
        - 2181:2181
    logging:
      driver: none
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    logging:
      driver: none
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "aerospike-sink:1:1,aerospike-source:1:1"
  aerospikedb:
    image: aerospike/aerospike-server:latest
    depends_on:
    - kafka
    ports:  
    - 3000:3000
    - 3001:3001
    volumes:
    - ./aerospike/etc:/etc/aerospike
    - ./aerospike/log:/aerospike/log
    - ./aerospike/data:/aerospike/data
    - ./aerospike/aql:/aerospike/aql
    environment:
      NAMESPACE: "test"
      MEM_GB: 12
    # command:
    # - /aerospike/aql/run-aql.sh
