version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
        - 2181:2181
    networks:
      - demo
    logging:
      driver: none
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    logging:
      driver: none
    ports:
      - 9092:9092
    networks:
      - demo
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "aerospike-source:1:1"
  kafkacli:
    image: taion809/kafka-cli:0.10.2.0
    command: kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic aerospike-source --from-beginning
    stdin_open: true
    tty: true
    networks:
      - demo
    links:
      - zookeeper
    depends_on:
      - zookeeper
  aerospikedb:
    container_name: aerospike-enterprise-server
    build:
      context: ./aerospike/enterprise-server/
      args:
        AEROSPIKE_USER_NAME: "<user name>"
        AEROSPIKE_PASSWORD: "<password>"
    depends_on:
    - kafka
    ports:  
    - 3000:3000
    - 3001:3001
    - 3002:3002
    - 3003:3003
    networks:
      demo:
        aliases:
          - aerospike
    volumes:
    - ./aerospike/etc:/etc/aerospike
    - ./aerospike/log:/aerospike/log
    - ./aerospike/data:/aerospike/data
  simulator:
    container_name: traffic_simulator
    build:
      context: ./traffic-simulator/
    networks:
      - demo
    links:
    - aerospikedb
    depends_on:
    - aerospikedb
networks:
  demo:
    driver: bridge